### ISSUE TITLE
Undo shortcut key does not uncomment multiple line at once

### ISSUE THREAD

**Issue by wtfz** [ArturoDent/toggle-comments#1]
Hi @ArturoDent. I'm not sure if this is intended feature or a bug but this is how it goes. After selecting multiple lines, I can comment my selection by line with the shortcut key and uncomment it back by using the same key again (while the same line is highlighted). However, when I tried to uncomment using the `Cmd+Z` (undo shortcut key) just after I comment it, it doesn't uncomment at once but rather it uncomment it line by line. My expectation was if I'm using the undo key, it will un-toggle back the thing I did before.

P/S - I have my comment key changed from default `Alt+Cmd+/` to `Cmd+/` (replacing VSC built-in shortcut).

**Comment by ArturoDent** [comment]
I don't believe this is possible right now.  VS Code itself can do this, wrapping a sequence of comment commands as one undo block.  See 

```js
editor.pushUndoStop();
editor.executeCommands(this.id, commands);
editor.pushUndoStop();
```

from [comments.ts in github](https://github.com/microsoft/vscode/blob/d31496c866683bdbccfc85bc11a3107d6c789b52/src/vs/editor/contrib/comment/comment.ts).

But that command `editor.pushUndoStop()` is not made available in the extension api unfortunately.  

I am going to close this issue as unavoidable.  I will keep my eye on the `undo`-related api commands.
